//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAE_Restaurante.Entidad.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int id_contactos { get; set; }
        public string nombre { get; set; }
        public string tipo_contacto { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentario { get; set; }
    }
}
