//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAE_Restaurante.Entidad.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAE_RestauranteEntities : DbContext
    {
        public BAE_RestauranteEntities()
            : base("name=BAE_RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comida> Comida { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Control> Control { get; set; }
        public virtual DbSet<Doc_compra> Doc_compra { get; set; }
        public virtual DbSet<Doc_venta> Doc_venta { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Ingrediente> Ingrediente { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Mesa> Mesa { get; set; }
        public virtual DbSet<Pedido> Pedido { get; set; }
        public virtual DbSet<Pedido_Comida> Pedido_Comida { get; set; }
        public virtual DbSet<Pedido_Producto> Pedido_Producto { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_comida> Tipo_comida { get; set; }
        public virtual DbSet<Tipo_medida> Tipo_medida { get; set; }
        public virtual DbSet<Tipo_producto> Tipo_producto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
