//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAE_Restaurante.Entidad.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc_compra()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int id_doc_compra { get; set; }
        public string tipo_doc_compra { get; set; }
        public int num_doc_compra { get; set; }
        public decimal venta_total { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
