//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAE_Restaurante.Entidad.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_venta
    {
        public int id_doc_venta { get; set; }
        public string tipo_doc_venta { get; set; }
        public int num_doc_venta { get; set; }
        public decimal venta_total { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentario { get; set; }
        public int id_pedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
