//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAE_Restaurante.Entidad.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        public int id_ingrediente { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string comentario { get; set; }
        public Nullable<int> id_tipo_medida { get; set; }
    
        public virtual Tipo_medida Tipo_medida { get; set; }
    }
}
