//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAE_Restaurante.Entidad.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Doc_venta = new HashSet<Doc_venta>();
            this.Pedido_Comida = new HashSet<Pedido_Comida>();
            this.Pedido_Producto = new HashSet<Pedido_Producto>();
        }
    
        public int id_pedido { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipo_pedido { get; set; }
        public string tipo_pago { get; set; }
        public Nullable<int> imagen_pago { get; set; }
        public string estado { get; set; }
        public string comentario { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public int id_cliente { get; set; }
        public Nullable<int> id_mesa { get; set; }
        public string direccion_envio { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doc_venta> Doc_venta { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Mesa Mesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Comida> Pedido_Comida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido_Producto> Pedido_Producto { get; set; }
    }
}
